### ISSUE TITLE
updateios fails " "Continue the installation [y|n]?"

### ISSUE THREAD

**Issue by lochaitis** [IBM/ansible-power-vios#6] opened 2020-11-28 12:05 UTC
updateios fails. When reviewing  the debug logs the last line looks like it waiting for input  "Continue the installation [y|n]?"]}". however when I login to the VIOS with the devops user and run the updateios command that works fine.
[install_all_updates.log](https://github.com/IBM/ansible-power-vios/files/5610546/install_all_updates.log)

Playbook entry is below.
- name: Update the VIOS to level 2.2.6.65, updates are mount on /home/devops/VIOS
       updateios: device=/home/devops/VIOS/VIOS_2.2.6.65 accept_licenses=true action=cleanup action=update

**Comment by dberg1** [comment] 2020-12-01 15:07
It is normal that you see this line in the logs. However, it should not be waiting (updateios command is run with "y\ny" answer as standard input, unless you are running in preview mode with ansible-playbook --check).
Can you share the logs containing this message? What error did ansible return? Or did it block?

**Comment by lochaitis** [comment] 2020-12-01 16:56
I am not running in preview mode as far as I know.

I am attaching the log from the VIOS server that I am trying to update and also the error on Ansible.

[ansible_error.txt](https://github.com/IBM/ansible-power-vios/files/5624118/ansible_error.txt)
[VIOS_install_all_updates.log](https://github.com/IBM/ansible-power-vios/files/5624119/VIOS_install_all_updates.log)

**Comment by dberg1** [comment] 2020-12-02 08:24
I think I understand what the problem is.
In my testing, updateios was only expecting one answer:
```
Continue the installation [y|n]?
```
Whereas in your case, it is expecting two answers:
```
Continue bos.rte.install installation [y|n]?
Continue the installation [y|n]?
```
That's because I did not have the `bos.rte.install` fileset in my test updates.
Unfortunately, there is a bug in the code that causes only the first 'y' answer to be sent to the command.
I have fixed this issue in our development repo. It will be fixed in the next PR.

**Comment by lochaitis** [comment] 2020-12-02 14:43
OK perfect, thanks for the clarification.

Is there any timeline for next PR ?

**Comment by dberg1** [comment] 2020-12-02 16:43
Should be made before the end of this week.

**Comment by pbfinley1911** [comment] 2020-12-06 00:52
Fix pack is now available via GitHub.
https://github.com/IBM/ansible-power-vios/releases/tag/v1.1.2-FP1

The Galaxy community and AH certified updates will not happen until Dec 28th.

**Closed as completed by pbfinley1911** 2020-12-06 00:52 UTC
